services:
  streamlit2:
    build: .
    ports:
      - 9501:9501
    volumes:
      - .:/app
      - ../nltk_data:/root/nltk_data
    command: [ "streamlit", "run", "/app/src/app/streamlit/main.py", "--server.port=9501", "--server.address=0.0.0.0", "--server.enableCORS=false", "--server.enableXsrfProtection=false", "--server.baseUrlPath=/archivep2/", "--server.enableWebsocketCompression=false" ]
  ##    command: ["streamlit", "run", "/app/src/app/streamlit/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
  archivep_api2:
    build: .
    ports:
      - 9005:9005
    volumes:
      - .:/app
      - ../nltk_data:/root/nltk_data
    command: python /app/src/app/api/main.py
    restart: "on-failure"
